### ISSUE TITLE
mac support

### ISSUE THREAD

**Issue by daiyanbao** [songgao/water#10]
it's a very strong project.

but not support osx,do you have some solution,the path /dev/net/tap and /dev/net/tun not exist in mac osx .

**Comment by songgao** [comment]
I just added TUN (point-to-point only) support for macOS since the kernel has built-in support for it. Hope it's useful!

I imagine TAP wouldn't possible without the `tuntaposx` kernel extension though. In the future, I'd like to have it dynamically detect if the kernel extension is loaded. So it can use it for full TUN/TAP support if it's available, and fallback to `utun` otherwise.

**Comment by daiyanbao** [comment]
i write cgo code to support macOS all last night....


  fd = socket (PF_SYSTEM, SOCK_DGRAM, SYSPROTO_CONTROL);
  //return fd;
  if (fd < 0) return fd;

  bzero(&info, sizeof (info));
  strncpy(info.ctl_name, UTUN_CONTROL_NAME, MAX_KCTL_NAME);

but your code is more useful,thank you.

**Comment by songgao** [comment]
Closing this as `tuntaposx` is mentioned in TODO section in README.md
