### ISSUE TITLE
收不到其他端口发送的包，why

### ISSUE THREAD

**Issue by gonewind73** [songgao/water#45]
我在测试tap端口时，无法收到其他端口的ping包，用ping -I enp0s3 10.0.42.1 。 但可以收到 ping -b 10.0.42.1 ，why？

func TestTAP(t *testing.T) {
	var (
		self = net.IPv4(10, 0, 42, 1)
		mask = net.IPv4Mask(255, 255, 255, 0)
		brd  = net.IPv4(10, 0, 42, 255)
	)
	fmt.Println("Start to test TAP!")
	ifce, err := New(Config{DeviceType: TAP})
	if err != nil {
		t.Fatalf("creating TAP error: %v\n", err)
	}

	setupIfce(t, net.IPNet{IP: self, Mask: mask}, ifce.Name())
	dataCh := make(chan []byte, 8)
	startRead(dataCh, ifce)

	timeout := time.NewTimer(5 * time.Second).C

readFrame:
	for {
		select {
		case buffer := <-dataCh:
			ethertype := waterutil.MACEthertype(buffer)
			if ethertype != waterutil.IPv4 {
				continue readFrame
			}

			packet := waterutil.MACPayload(buffer)
			if !waterutil.IsIPv4(packet) {
				continue readFrame
			}
			if !waterutil.IPv4Destination(packet).Equal(self) {
				continue readFrame
			}
			if waterutil.IPv4Protocol(packet) != waterutil.ICMP {
				continue readFrame
			}
			t.Logf("received broadcast frame: %#v\n", buffer)
			break readFrame
		case <-timeout:
			t.Fatal("Waiting for ping packet timeout")
		}
	}
}

**Comment by songgao** [comment]
First of all, you set 10.0.42.1 on the created interface, meaning it is an IP on the same machine. So kernel may bypass the packets and deliver them directly rather than going through the TUN/TAP driver. See https://github.com/songgao/water/issues/42

Secondly, it seems you are sending through a real network interface `enp0s3` by using `-I`. I think even if it were not the same machine, it would’ve been sent out through that physical interface.

**Comment by gonewind73** [comment]
you are right. thanks.
